### ISSUE TITLE
[TODO]

### ISSUE THREAD

**Issue by nudago** [16Dorm/home-training#1]
- [ ] 이미지 별 Max Y값 구하기 - 병국
- [ ] Max Y값으로 0,1,2레이블 분리 - 세진
- [ ] 이미지, 레이블명으로 CSV파일 생성 - 요한
- [ ] 파이토치로 이미지, 레이블 데이터 로드 - 광우
