### ISSUE TITLE
[TODO] [2021.10.26] 실시간 예측 모델 구현

### ISSUE THREAD

**Issue by BumBamBi** [16Dorm/home-training#11]
- [x] SupervisedLearning.py 입력(실시간 프레임 좌표)/리턴(예측 레이블 값) 해서 함수로 만들기 - 병국

- [x] 병국이가 만든 함수의 리턴값을 이용해서 카운트 함수 만들기 - 광우

- [x] 실시간으로 영상 실행시켜보기 - 추후 요한/세진
