### ISSUE TITLE
[TODO] [2021.10.28] GUI 및 AWS 방향 선택 전 마무리 정리

### ISSUE THREAD

**Issue by BumBamBi** [16Dorm/home-training#12]
- [x] 3 2 1 2 3 중, 단 하나의 프레임이라도 오차일 시 노카운트 -> 3개?의 오차 허용   - 광우
- [x] 실시간으로 수행해보기 - 세진
- [x] 코드 정리 - 요한
- [x] GUI버젼으로 브랜치 하기 - 요한
- [ ] Flask를 이용한 PC-Mobile 연동(영상 불러오기) - 병국

---

GUI 만들기(PyQT5)
- [x] 시작화면 (목표치 설정, 시작버튼)
- [x] 구현 동영상
- [x] 결과화면 (횟수, 정확도, 운동량, 리플레이)
