### ISSUE TITLE
[TODO] [2021.11.02] GUI 구현

### ISSUE THREAD

**Issue by BumBamBi** [16Dorm/home-training#14]
AI
	- [ ] 실시간 들어온 영상 저장

결과창
	- [ ] 뭐 나오게할지
	- [ ] 디자인 어떻게 할지
	- [ ] 리플레이 버튼 - 저장영상 실행
	- [ ] 끝 버튼 - 저장영상 삭제
	- [ ] 홈 버튼
