### ISSUE TITLE
[TODO] 2021.09.02

### ISSUE THREAD

**Issue by nudago** [16Dorm/home-training#3]
- [ ] 엎드리는 과정 영상찍고 레이블 0 만들기 

- [ ] 세 좌표 (엉덩이, 무릎각도) 좌표 추가 - 병국
- [ ] 선형분류기 코드 업로드

- [ ] 나온 각도를 확인 후 라벨링 할때 적용 - 광우
