### ISSUE TITLE
[TODO] [2021.09.29] 앞으로 진행해야할 상황

### ISSUE THREAD

**Issue by nudago** [16Dorm/home-training#5]
## 1. 동작 상태분류
- [ ] definelable함수 -> 데이터셋를 보조 -> Classifier를 학습 -> 좋은 성능
- [ ] 데이터셋에 잘못된거? 확인 필요
- [ ] Classifier 선택
    - [ ] Naive baysian Classifier
    - [ ] CNN DL Approach

## 2. 오동작 분류
- [ ] (각 키포인트 비교) defineLabel() -> 빨간점찍는것
- [ ] (순간 (좌표,각도))에 대해 코사인 Similarity -> 유사도가 떨어지는것들만 -> DefinLabel 빨간점
